### ISSUE TITLE
UndefinedBehaviorError when trying to access response headers

### ISSUE THREAD

**Issue by 2m** [hmil/RosHTTP#60]
I get a `UndefinedBehaviorError: An undefined behavior was detected: test=test is not an instance of java.lang.String` when trying to access response headers like so:

```
val resp = HttpRequest("https://cors-test.appspot.com/test")
      .send()
      .map(resp => resp.headers.get("Set-Cookie").map(_.toString.toUpperCase))
```

I found a workaround, which is to cast the String to `js.Any` and back to String:

```
val resp = HttpRequest("https://cors-test.appspot.com/test")
      .send()
      .map(resp => (resp.headers.get("Set-Cookie").asInstanceOf[Option[js.Any]]).map(_.toString.toUpperCase))
```

Some discussion: https://gitter.im/scala-js/scala-js?at=587bc962db9cafe9183c9644

**Comment by hmil** [comment]
Can you create a reproductible test-case for this? (Maybe querying something everyone has access to). Also in which environment(s) does this occur?

**Comment by hmil** [comment]
Seems like a dup of #68
