### ISSUE TITLE
Make RosHTTP work with scalsjs-bundler

### ISSUE THREAD

**Issue by Mahoney** [hmil/RosHTTP#69]
I'm trying to convert my project to [scalajs-bundler](https://github.com/scalacenter/scalajs-bundler) to make it easier to depend on npm libraries. However, this breaks RosHTTP, because RosHTTP [tries to detect whether to use the Node JS driver or the Browser driver based on whether require is defined](https://github.com/hmil/RosHTTP/blob/master/js/src/main/scala/fr/hmil/roshttp/HttpDriver.scala) - and the scala js bundler loader defines a top level require function.

I suspect it would be nicest to split RosHTTP into four libraries - a cross compiled interface, and three implementations, one for the JVM, one for Node and one for the browser. Then instead of trying to calculate the implementation at runtime it can be done at compile time.

**Comment by Mahoney** [comment]
However, a quick solution can be found in this pull request:
https://github.com/hmil/RosHTTP/pull/70

**Comment by hmil** [comment]
Done in #70
