### ISSUE TITLE
Dependency on Monix 2.3.0 Broken

### ISSUE THREAD

**Issue by Vance-Turner** [hmil/RosHTTP#85]
The dependency on Monix 2.3.0 is broken due to the JAR being unavailable. Monix version 2.3.3 is available though.

**Comment by hmil** [comment]
Hi, thanks for the heads up. I'll take care of this.

**Comment by hmil** [comment]
Wait a minute, which JAR is unavailable? I just tested and it worked, also there doesn't seem to be anything missing from maven central.

**Comment by Vance-Turner** [comment]
The 2.3.0 jar here isn't available: https://repo1.maven.org/maven2/io/monix/monix_2.12/2.3.0/

**Comment by hmil** [comment]
@Vance-Turner I just released v2.2.4. Can you try that and tell me if it works?
