### ISSUE TITLE
Feature Support for SSLContext

### ISSUE THREAD

**Issue by Hakky54** [hmil/RosHTTP#91]
Hi,

Thank you for this awesome http client. I noticed that there is no option to pass an instance of SSLContext within the requests. It would be great to have that option as well for https requests which will enable me and other developers to use a custom list of trusted certificates or even provide a custom client certificate as well for mutual authentication. Would that be possible?

Kinds regards,
Hakan

**Comment by hmil** [comment]
Hello @Hakky54 ,

I am not actively working on this project at this time but I am willing to help if people submit pull requests.

Can you describe in more details what you want to achieve? What would SSLContext allow you to do? How would this feature behave across the platforms supported by RosHTTP (jvm, node and browser)?

**Comment by Hakky54** [comment]
What I want to achieve is to execute a https request to a server which the client needs to trust or else the ssl handshake will fail and the request would also fail. The most used class for this case within different java/scala/kotlin based http clients would be the [SSLContext](https://docs.oracle.com/javase/7/docs/api/javax/net/ssl/SSLContext.html) or [TrustManager](https://docs.oracle.com/javase/7/docs/api/javax/net/ssl/X509ExtendedTrustManager.html) and [KeyManager](https://docs.oracle.com/javase/7/docs/api/javax/net/ssl/X509ExtendedKeyManager.html). Another use case would be mutual authentication where the server requires the client to identifies itself with his certificate. In that case RosHTTP somehow needs to provide his certificate, but that will only be possible with the SSLContext or a KeyManager.

I discovered within the jvm source code of RosHTTP that it is using the java net http client with HttpURLConnection. This class has the ability to load the ssl property with the method [HttpsURLConnection#setSSLSocketFactory](https://docs.oracle.com/javase/7/docs/api/javax/net/ssl/HttpsURLConnection.html#setSSLSocketFactory(javax.net.ssl.SSLSocketFactory)). This method expects a SocketFactory which is available within the [SSLContext#getSocketFactory](https://docs.oracle.com/javase/7/docs/api/javax/net/ssl/SSLContext.html#getSocketFactory()).

I would expect the same behaviour from the node platform, but I am note quite sure how the implementation would be. I am familiar with Scala so I can give an attempt for a pull request. 

What do you think of the feature, do you think this would be a good additional feature for this project?

**Comment by hmil** [comment]
I think that a custom abstraction would have to be defined in RosHTTP such that users aren't exposed to SSLContext directly.

On the JVM, this abstraction could be backed by SSLContext / TrustManager and others.
In node.js, it could be using the `key` and `cert` options of [https.request](https://nodejs.org/docs/latest-v13.x/api/https.html#https_https_request_options_callback)
In the browser, this would not be supported. JavaScript does not have control over client certificates in the browser.

**Comment by Hakky54** [comment]
Custom abstraction sounds good. 

Within node it is possible to load the keymaterial in two different ways either by providing separate key and cert file as a pem file or by providing a pfx/p12 file. Either way is quite easy to implement within node, but with the jvm version loading a separate key and cert file as a pem file would the troublesome as the header of the private key is different for each algorithm, see here for an example for rsa: `-----BEGIN RSA PRIVATE KEY-----`. I don't prefer having a logic to handle all types of headers of the private key for parsing as I think it would also make it more error prone. But if we decide to use the pfx/p12 format to load the keymaterial it would be less verbose than the other option.

Regarding loading the list of trusted certificates I would propose to use `ca ` field for node js. This option can only load a pem file. The jvm would require some additional logic to parse the pem file, but much easier compared to parsing the private key.

I would like to propose these changes within the BackendConfig, so the individual HttpDrivers can have their own implementation of loading the files. The BackendConfig would than have the following additional parameter: `val sslConfig: Option[SSLConfig]` and by default this would be empty.

An example SSLConfig class mention above could be something like this:
```
class SSLConfig private(
    val keyStorePath: Option[String],
    val keyStorePassphrase: Option[Array[Char]],
    val trustStorePaths: Option[Array[String]]
)
```

What do you think of this proposal?

**Comment by hmil** [comment]
Sounds good. Let's discuss implementation details on the PR.

**Comment by Hakky54** [comment]
Sure, I created already a pull request with some questions. Please have a look at it here: https://github.com/hmil/RosHTTP/pull/92

**Comment by Hakky54** [comment]
I am closing this issue as the owner has mentioned here: https://github.com/hmil/RosHTTP/commit/8bf579ab89af4bee61a7708560a8731dfb011871 that it is not maintaining this library for now. I also closed the pull request
