### ISSUE TITLE
Bintray repository is gone

### ISSUE THREAD

**Issue by nondeterministic** [hmil/RosHTTP#93]
I saw you don't maintain RosHttp anymore, but you may want to keep it downloadable, which currently it isn't as the bintray repository no longer exists.

So, my question is: are you going to release the current state as-is somewhere else, or would you want someone else to make an attempt at a release?  I seem to remember you moving to bintray because the maven-central release process was somewhat broken. I'd be volunteering to try it and release the current RosHttp there (I have released a few minor things there in the past), but I'm not yet confident about the outcome...

I have to re-read how all the package signing etc. works and if I can release without changing your authorship in `build.sbt`, for example. But anyway: I'd be willing to give it a shot, unless you're going to re-release your current version yourself.

**Comment by 2m** [comment]
FWIW: I have been having great experience with https://github.com/olafurpg/sbt-ci-release when migrating a couple of projects (libraries, sbt plugins) from Bintray to Maven Central lately.

**Comment by hmil** [comment]
Thanks for the suggestion @2m . Sounds like a good exercise to get myself familiar with GitHub actions.
Not only is bintray gone, but most of my builds run on travis-ci.org which is also going away too 😭  I suppose GH actions are the new go-to now?

Also, as previously stated feel free to fork this project and make it yours. Even change the package from `fr.hmil` to something else if that helps.

**Comment by 2m** [comment]
Yup. I migrated to GH Actions as well.

**Comment by hmil** [comment]
OK you know what, screw that. I'm hosting the files on my private server. Should have done this from the beginning so I wouldn't have had to deal with a situation like this in the first place. SaaS providers come and go but the one thing which has never failed me is my old trusty private server. The web is supposed to be decentralised after all.

I tested this locally and it seems to work:

```
resolvers += "hmil.fr" at "https://files.hmil.fr/maven/"

libraryDependencies += "fr.hmil" %%% "roshttp" % "3.0.0"
```

Let me know if it works for you and I'll update the readme.

**Comment by nondeterministic** [comment]
Many thanks for looking into that! Your self-hosting approach seems reasonable to me. After all, the "package landscape" is scattered as it is.
Two comments though:
1. I think, it has to be "fr.hmil" and not "hmil.fr" in the resolvers.
2. I get the following error, when using it. It seems, the `-3.0.0` part would be present, if it was a "proper" maven package (cf.  https://repo1.maven.org/maven2/fr/hmil/scala-http-client_sjs0.6_2.11/0.3.0/):
```
[error] sbt.librarymanagement.ResolveException: Error downloading fr.hmil:roshttp_sjs1_2.13:3.0.0
[error]   Not found
[error]   Not found
[error]   not found: /home/baueran/.ivy2/local/fr.hmil/roshttp_sjs1_2.13/3.0.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/fr/hmil/roshttp_sjs1_2.13/3.0.0/roshttp_sjs1_2.13-3.0.0.pom
[error]   not found: https://files.hmil.fr/maven/fr/hmil/roshttp_sjs1_2.13/3.0.0/roshttp_sjs1_2.13-3.0.0.pom
```
But perhaps, I'm missing something obvious here.

**Comment by hmil** [comment]
> But perhaps, I'm missing something obvious here.

No I think I got it wrong. Try again now.

**Comment by nondeterministic** [comment]
Just tried again, it all seems to work fine now. Thanks for fixing it!

**Comment by hmil** [comment]
Great. Regarding the `resolvers` line, I think the first part is just a name you give the resolver locally. You could put anything you want there. The part which really matters is the URL.
